/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_liang_com_demo_TestComlib */



#ifndef _Included_com_example_liang_com_demo_TestComlib
#define _Included_com_example_liang_com_demo_TestComlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_liang_com_demo_TestComlib
 * Method:    Init_COM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_liang_com_1demo_TestComlib_Init_1COM
  (JNIEnv *, jobject);

/*
 * Class:     com_example_liang_com_demo_TestComlib
 * Method:    Send_COM
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_liang_com_1demo_TestComlib_Send_1COM
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_liang_com_demo_TestComlib
 * Method:    Read_COM
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_liang_com_1demo_TestComlib_Read_1COM
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
